# Generated by Django 3.1.7 on 2021-03-31 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_code', to='users.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'VerificationCode',
                'verbose_name_plural': 'VerificationCodes',
                'abstract': False,
            },
        ),
    ]
