# Generated by Django 3.1.7 on 2021-04-03 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqsStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(choices=[('SUD', 'Simple User Data')], default='SUD', max_length=3)),
                ('request', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_reqs_stat', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
