# Generated by Django 3.1.7 on 2021-04-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reqs_stat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqsstat',
            name='request',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Requested'),
        ),
    ]
